// <auto-generated />
using System;
using Doctrina.Domain.Entities;
using Doctrina.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Doctrina.Persistence.Migrations
{
    [DbContext(typeof(DoctrinaDbContext))]
    partial class DoctrinaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Doctrina.Domain.Entities.Account", b =>
                {
                    b.Property<Guid>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("HomePage")
                        .HasColumnType("character varying(2083)")
                        .HasMaxLength(2083);

                    b.Property<string>("Name")
                        .HasColumnType("character varying(40)")
                        .HasMaxLength(40);

                    b.HasKey("AccountId");

                    b.ToTable("AgentAccounts");
                });

            modelBuilder.Entity("Doctrina.Domain.Entities.ActivityDefinitionEntity", b =>
                {
                    b.Property<Guid>("ActivityDefinitionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descriptions")
                        .HasColumnType("varchar");

                    b.Property<string>("Extensions")
                        .HasColumnType("varchar");

                    b.Property<Guid?>("InteractionActivityInteractionId")
                        .HasColumnType("uuid");

                    b.Property<string>("MoreInfo")
                        .HasColumnType("text");

                    b.Property<string>("Names")
                        .HasColumnType("varchar");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("ActivityDefinitionId");

                    b.HasIndex("InteractionActivityInteractionId");

                    b.ToTable("ActivityDefinitions");
                });

            modelBuilder.Entity("Doctrina.Domain.Entities.ActivityEntity", b =>
                {
                    b.Property<Guid>("ActivityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DefinitionActivityDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("character varying(40)")
                        .HasMaxLength(40);

                    b.Property<string>("Id")
                        .IsRequired()
                        .HasColumnType("character varying(2083)")
                        .HasMaxLength(2083);

                    b.HasKey("ActivityId");

                    b.HasIndex("DefinitionActivityDefinitionId");

                    b.HasIndex("Hash")
                        .IsUnique();

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("Doctrina.Domain.Entities.AgentEntity", b =>
                {
                    b.Property<Guid>("AgentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("GroupEntityAgentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("character varying(40)")
                        .HasMaxLength(40);

                    b.Property<string>("Mbox")
                        .HasColumnName("Mbox")
                        .HasColumnType("character varying(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Mbox_SHA1SUM")
                        .HasColumnName("Mbox_SHA1SUM")
                        .HasColumnType("character varying(40)")
                        .HasMaxLength(40);

                    b.Property<string>("Name")
                        .HasColumnType("character varying(100)")
                        .HasMaxLength(100);

                    b.Property<int>("ObjectType")
                        .HasColumnType("integer");

                    b.Property<string>("OpenId")
                        .HasColumnName("OpenId")
                        .HasColumnType("text");

                    b.HasKey("AgentId");

                    b.HasIndex("AccountId");

                    b.HasIndex("GroupEntityAgentId");

                    b.HasIndex("ObjectType", "Hash")
                        .IsUnique();

                    b.ToTable("Agents");

                    b.HasDiscriminator<int>("ObjectType").HasValue(1);
                });

            modelBuilder.Entity("Doctrina.Domain.Entities.AttachmentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Description")
                        .HasColumnType("varchar");

                    b.Property<string>("Display")
                        .IsRequired()
                        .HasColumnType("varchar");

                    b.Property<string>("FileUrl")
                        .HasColumnType("text");

                    b.Property<int>("Length")
                        .HasColumnType("integer");

                    b.Property<byte[]>("Payload")
                        .HasColumnType("bytea");

                    b.Property<string>("SHA2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("StatementEntityStatementId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SubStatementEntitySubStatementId")
                        .HasColumnType("uuid");

                    b.Property<string>("UsageType")
                        .IsRequired()
                        .HasColumnType("character varying(2083)")
                        .HasMaxLength(2083);

                    b.HasKey("Id");

                    b.HasIndex("StatementEntityStatementId");

                    b.HasIndex("SubStatementEntitySubStatementId");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("Doctrina.Domain.Entities.ContextActivitiesEntity", b =>
                {
                    b.Property<Guid>("ContextActivitiesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("ContextActivitiesId");

                    b.ToTable("ContextActivities");
                });

            modelBuilder.Entity("Doctrina.Domain.Entities.ContextEntity", b =>
                {
                    b.Property<Guid>("ContextId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ContextActivitiesId")
                        .HasColumnType("uuid");

                    b.Property<string>("Extensions")
                        .HasColumnType("varchar");

                    b.Property<Guid?>("InstructorAgentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Language")
                        .HasColumnType("text");

                    b.Property<string>("Platform")
                        .HasColumnType("text");

                    b.Property<Guid?>("Registration")
                        .HasColumnType("uuid");

                    b.Property<string>("Revision")
                        .HasColumnType("text");

                    b.Property<Guid?>("TeamAgentId")
                        .HasColumnType("uuid");

                    b.HasKey("ContextId");

                    b.HasIndex("ContextActivitiesId");

                    b.HasIndex("InstructorAgentId");

                    b.HasIndex("TeamAgentId");

                    b.ToTable("Contexts");
                });

            modelBuilder.Entity("Doctrina.Domain.Entities.Documents.ActivityProfileEntity", b =>
                {
                    b.Property<Guid>("ActivityProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActivityId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("RegistrationId")
                        .HasColumnType("uuid");

                    b.HasKey("ActivityProfileId");

                    b.HasIndex("ActivityId");

                    b.ToTable("ActivityProfiles");
                });

            modelBuilder.Entity("Doctrina.Domain.Entities.Documents.ActivityStateEntity", b =>
                {
                    b.Property<Guid>("ActivityStateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActivityId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("Registration")
                        .HasColumnType("uuid");

                    b.Property<string>("StateId")
                        .IsRequired()
                        .HasColumnType("character varying(2083)")
                        .HasMaxLength(2083);

                    b.HasKey("ActivityStateId");

                    b.HasIndex("ActivityId");

                    b.HasIndex("AgentId");

                    b.ToTable("ActivityStates");
                });

            modelBuilder.Entity("Doctrina.Domain.Entities.Documents.AgentProfileEntity", b =>
                {
                    b.Property<Guid>("AgentProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasColumnType("character varying(2083)")
                        .HasMaxLength(2083);

                    b.HasKey("AgentProfileId");

                    b.HasIndex("AgentId");

                    b.HasIndex("ProfileId")
                        .IsUnique();

                    b.ToTable("AgentProfiles");
                });

            modelBuilder.Entity("Doctrina.Domain.Entities.InteractionActivities.InteractionActivityBase", b =>
                {
                    b.Property<Guid>("InteractionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CorrectResponsesPattern")
                        .HasColumnType("text");

                    b.Property<string>("InteractionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("InteractionId");

                    b.ToTable("InteractionActivities");

                    b.HasDiscriminator<string>("InteractionType").HasValue("InteractionActivityBase");
                });

            modelBuilder.Entity("Doctrina.Domain.Entities.ResultEntity", b =>
                {
                    b.Property<Guid>("ResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool?>("Completion")
                        .HasColumnType("boolean");

                    b.Property<string>("Duration")
                        .HasColumnType("text");

                    b.Property<long?>("DurationTicks")
                        .HasColumnType("bigint");

                    b.Property<string>("Extensions")
                        .HasColumnType("varchar");

                    b.Property<string>("Response")
                        .HasColumnType("text");

                    b.Property<bool?>("Success")
                        .HasColumnType("boolean");

                    b.HasKey("ResultId");

                    b.ToTable("Results");
                });

            modelBuilder.Entity("Doctrina.Domain.Entities.StatementEntity", b =>
                {
                    b.Property<Guid>("StatementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActorAgentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AuthorityId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ContextId")
                        .HasColumnType("uuid");

                    b.Property<string>("FullStatement")
                        .HasColumnType("text");

                    b.Property<Guid?>("ResultId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("Stored")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("Timestamp")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VerbId")
                        .HasColumnType("uuid");

                    b.Property<string>("Version")
                        .HasColumnType("character varying(7)")
                        .HasMaxLength(7);

                    b.Property<bool>("Voided")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.HasKey("StatementId");

                    b.HasIndex("ActorAgentId");

                    b.HasIndex("AuthorityId");

                    b.HasIndex("ContextId");

                    b.HasIndex("ResultId");

                    b.HasIndex("VerbId");

                    b.ToTable("Statements");
                });

            modelBuilder.Entity("Doctrina.Domain.Entities.StatementRefEntity", b =>
                {
                    b.Property<Guid>("StatementRefId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("StatementId")
                        .HasColumnType("uuid");

                    b.HasKey("StatementRefId");

                    b.HasIndex("StatementId");

                    b.ToTable("StatementRefs");
                });

            modelBuilder.Entity("Doctrina.Domain.Entities.SubStatementEntity", b =>
                {
                    b.Property<Guid>("SubStatementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActorAgentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ContextId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ResultId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("Timestamp")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VerbId")
                        .HasColumnType("uuid");

                    b.HasKey("SubStatementId");

                    b.HasIndex("ActorAgentId");

                    b.HasIndex("ContextId");

                    b.HasIndex("ResultId");

                    b.HasIndex("VerbId");

                    b.ToTable("SubStatements");
                });

            modelBuilder.Entity("Doctrina.Domain.Entities.VerbEntity", b =>
                {
                    b.Property<Guid>("VerbId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Display")
                        .HasColumnType("varchar");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("character varying(40)")
                        .HasMaxLength(40);

                    b.Property<string>("Id")
                        .IsRequired()
                        .HasColumnType("character varying(2083)")
                        .HasMaxLength(2083);

                    b.HasKey("VerbId");

                    b.HasIndex("Hash")
                        .IsUnique();

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Verbs");
                });

            modelBuilder.Entity("Doctrina.Domain.Entities.GroupEntity", b =>
                {
                    b.HasBaseType("Doctrina.Domain.Entities.AgentEntity");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("Doctrina.Domain.Entities.InteractionActivities.ChoiceInteractionActivity", b =>
                {
                    b.HasBaseType("Doctrina.Domain.Entities.InteractionActivities.InteractionActivityBase");

                    b.Property<string>("Choices")
                        .HasColumnType("varchar");

                    b.HasDiscriminator().HasValue("choice");
                });

            modelBuilder.Entity("Doctrina.Domain.Entities.InteractionActivities.FillInInteractionActivity", b =>
                {
                    b.HasBaseType("Doctrina.Domain.Entities.InteractionActivities.InteractionActivityBase");

                    b.HasDiscriminator().HasValue("fill-in");
                });

            modelBuilder.Entity("Doctrina.Domain.Entities.InteractionActivities.LikertInteractionActivity", b =>
                {
                    b.HasBaseType("Doctrina.Domain.Entities.InteractionActivities.InteractionActivityBase");

                    b.Property<string>("Scale")
                        .HasColumnType("varchar");

                    b.HasDiscriminator().HasValue("likert");
                });

            modelBuilder.Entity("Doctrina.Domain.Entities.InteractionActivities.LongFillInInteractionActivity", b =>
                {
                    b.HasBaseType("Doctrina.Domain.Entities.InteractionActivities.InteractionActivityBase");

                    b.HasDiscriminator().HasValue("long-fill-in");
                });

            modelBuilder.Entity("Doctrina.Domain.Entities.InteractionActivities.MatchingInteractionActivity", b =>
                {
                    b.HasBaseType("Doctrina.Domain.Entities.InteractionActivities.InteractionActivityBase");

                    b.Property<string>("Source")
                        .HasColumnType("varchar");

                    b.Property<string>("Target")
                        .HasColumnType("varchar");

                    b.HasDiscriminator().HasValue("matching");
                });

            modelBuilder.Entity("Doctrina.Domain.Entities.InteractionActivities.NumericInteractionType", b =>
                {
                    b.HasBaseType("Doctrina.Domain.Entities.InteractionActivities.InteractionActivityBase");

                    b.HasDiscriminator().HasValue("NumericInteractionType");
                });

            modelBuilder.Entity("Doctrina.Domain.Entities.InteractionActivities.OtherInteractionActivity", b =>
                {
                    b.HasBaseType("Doctrina.Domain.Entities.InteractionActivities.InteractionActivityBase");

                    b.HasDiscriminator().HasValue("other");
                });

            modelBuilder.Entity("Doctrina.Domain.Entities.InteractionActivities.PerformanceInteractionActivity", b =>
                {
                    b.HasBaseType("Doctrina.Domain.Entities.InteractionActivities.InteractionActivityBase");

                    b.Property<string>("Steps")
                        .HasColumnType("varchar");

                    b.HasDiscriminator().HasValue("performance");
                });

            modelBuilder.Entity("Doctrina.Domain.Entities.InteractionActivities.SequencingInteractionActivity", b =>
                {
                    b.HasBaseType("Doctrina.Domain.Entities.InteractionActivities.InteractionActivityBase");

                    b.Property<string>("Choices")
                        .HasColumnName("SequencingInteractionActivity_Choices")
                        .HasColumnType("varchar");

                    b.HasDiscriminator().HasValue("sequencing");
                });

            modelBuilder.Entity("Doctrina.Domain.Entities.InteractionActivities.TrueFalseInteractionActivity", b =>
                {
                    b.HasBaseType("Doctrina.Domain.Entities.InteractionActivities.InteractionActivityBase");

                    b.HasDiscriminator().HasValue("true-false");
                });

            modelBuilder.Entity("Doctrina.Domain.Entities.ActivityDefinitionEntity", b =>
                {
                    b.HasOne("Doctrina.Domain.Entities.InteractionActivities.InteractionActivityBase", "InteractionActivity")
                        .WithMany()
                        .HasForeignKey("InteractionActivityInteractionId");
                });

            modelBuilder.Entity("Doctrina.Domain.Entities.ActivityEntity", b =>
                {
                    b.HasOne("Doctrina.Domain.Entities.ActivityDefinitionEntity", "Definition")
                        .WithMany()
                        .HasForeignKey("DefinitionActivityDefinitionId");
                });

            modelBuilder.Entity("Doctrina.Domain.Entities.AgentEntity", b =>
                {
                    b.HasOne("Doctrina.Domain.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId");

                    b.HasOne("Doctrina.Domain.Entities.GroupEntity", null)
                        .WithMany("Members")
                        .HasForeignKey("GroupEntityAgentId");
                });

            modelBuilder.Entity("Doctrina.Domain.Entities.AttachmentEntity", b =>
                {
                    b.HasOne("Doctrina.Domain.Entities.StatementEntity", null)
                        .WithMany("Attachments")
                        .HasForeignKey("StatementEntityStatementId");

                    b.HasOne("Doctrina.Domain.Entities.SubStatementEntity", null)
                        .WithMany("Attachments")
                        .HasForeignKey("SubStatementEntitySubStatementId");
                });

            modelBuilder.Entity("Doctrina.Domain.Entities.ContextActivitiesEntity", b =>
                {
                    b.OwnsMany("Doctrina.Domain.Entities.OwnedTypes.ContextActivityEntity", "Category", b1 =>
                        {
                            b1.Property<Guid>("ContextActivitiesEntityContextActivitiesId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("ActivityId")
                                .HasColumnType("text");

                            b1.Property<string>("Hash")
                                .HasColumnType("text");

                            b1.HasKey("ContextActivitiesEntityContextActivitiesId", "Id");

                            b1.ToTable("ContextActivities_Category");

                            b1.WithOwner()
                                .HasForeignKey("ContextActivitiesEntityContextActivitiesId");
                        });

                    b.OwnsMany("Doctrina.Domain.Entities.OwnedTypes.ContextActivityEntity", "Grouping", b1 =>
                        {
                            b1.Property<Guid>("ContextActivitiesEntityContextActivitiesId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("ActivityId")
                                .HasColumnType("text");

                            b1.Property<string>("Hash")
                                .HasColumnType("text");

                            b1.HasKey("ContextActivitiesEntityContextActivitiesId", "Id");

                            b1.ToTable("ContextActivities_Grouping");

                            b1.WithOwner()
                                .HasForeignKey("ContextActivitiesEntityContextActivitiesId");
                        });

                    b.OwnsMany("Doctrina.Domain.Entities.OwnedTypes.ContextActivityEntity", "Other", b1 =>
                        {
                            b1.Property<Guid>("ContextActivitiesEntityContextActivitiesId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("ActivityId")
                                .HasColumnType("text");

                            b1.Property<string>("Hash")
                                .HasColumnType("text");

                            b1.HasKey("ContextActivitiesEntityContextActivitiesId", "Id");

                            b1.ToTable("ContextActivities_Other");

                            b1.WithOwner()
                                .HasForeignKey("ContextActivitiesEntityContextActivitiesId");
                        });

                    b.OwnsMany("Doctrina.Domain.Entities.OwnedTypes.ContextActivityEntity", "Parent", b1 =>
                        {
                            b1.Property<Guid>("ContextActivitiesEntityContextActivitiesId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("ActivityId")
                                .HasColumnType("text");

                            b1.Property<string>("Hash")
                                .HasColumnType("text");

                            b1.HasKey("ContextActivitiesEntityContextActivitiesId", "Id");

                            b1.ToTable("ContextActivities_Parent");

                            b1.WithOwner()
                                .HasForeignKey("ContextActivitiesEntityContextActivitiesId");
                        });
                });

            modelBuilder.Entity("Doctrina.Domain.Entities.ContextEntity", b =>
                {
                    b.HasOne("Doctrina.Domain.Entities.ContextActivitiesEntity", "ContextActivities")
                        .WithMany()
                        .HasForeignKey("ContextActivitiesId");

                    b.HasOne("Doctrina.Domain.Entities.AgentEntity", "Instructor")
                        .WithMany()
                        .HasForeignKey("InstructorAgentId");

                    b.HasOne("Doctrina.Domain.Entities.AgentEntity", "Team")
                        .WithMany()
                        .HasForeignKey("TeamAgentId");
                });

            modelBuilder.Entity("Doctrina.Domain.Entities.Documents.ActivityProfileEntity", b =>
                {
                    b.HasOne("Doctrina.Domain.Entities.ActivityEntity", "Activity")
                        .WithMany()
                        .HasForeignKey("ActivityId");

                    b.OwnsOne("Doctrina.Domain.Entities.Documents.DocumentEntity", "Document", b1 =>
                        {
                            b1.Property<Guid>("ActivityProfileEntityActivityProfileId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Checksum")
                                .IsRequired()
                                .HasColumnType("character varying(50)")
                                .HasMaxLength(50);

                            b1.Property<byte[]>("Content")
                                .HasColumnType("bytea");

                            b1.Property<string>("ContentType")
                                .HasColumnType("character varying(255)")
                                .HasMaxLength(255);

                            b1.Property<DateTimeOffset>("CreateDate")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTimeOffset?>("LastModified")
                                .ValueGeneratedOnAddOrUpdate()
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("ActivityProfileEntityActivityProfileId");

                            b1.ToTable("ActivityProfiles");

                            b1.WithOwner()
                                .HasForeignKey("ActivityProfileEntityActivityProfileId");
                        });
                });

            modelBuilder.Entity("Doctrina.Domain.Entities.Documents.ActivityStateEntity", b =>
                {
                    b.HasOne("Doctrina.Domain.Entities.ActivityEntity", "Activity")
                        .WithMany()
                        .HasForeignKey("ActivityId");

                    b.HasOne("Doctrina.Domain.Entities.AgentEntity", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId");

                    b.OwnsOne("Doctrina.Domain.Entities.Documents.DocumentEntity", "Document", b1 =>
                        {
                            b1.Property<Guid>("ActivityStateEntityActivityStateId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Checksum")
                                .IsRequired()
                                .HasColumnType("character varying(50)")
                                .HasMaxLength(50);

                            b1.Property<byte[]>("Content")
                                .HasColumnType("bytea");

                            b1.Property<string>("ContentType")
                                .HasColumnType("character varying(255)")
                                .HasMaxLength(255);

                            b1.Property<DateTimeOffset>("CreateDate")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTimeOffset?>("LastModified")
                                .ValueGeneratedOnAddOrUpdate()
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("ActivityStateEntityActivityStateId");

                            b1.ToTable("ActivityStates");

                            b1.WithOwner()
                                .HasForeignKey("ActivityStateEntityActivityStateId");
                        });
                });

            modelBuilder.Entity("Doctrina.Domain.Entities.Documents.AgentProfileEntity", b =>
                {
                    b.HasOne("Doctrina.Domain.Entities.AgentEntity", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId");

                    b.OwnsOne("Doctrina.Domain.Entities.Documents.DocumentEntity", "Document", b1 =>
                        {
                            b1.Property<Guid>("AgentProfileEntityAgentProfileId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Checksum")
                                .IsRequired()
                                .HasColumnType("character varying(50)")
                                .HasMaxLength(50);

                            b1.Property<byte[]>("Content")
                                .HasColumnType("bytea");

                            b1.Property<string>("ContentType")
                                .HasColumnType("character varying(255)")
                                .HasMaxLength(255);

                            b1.Property<DateTimeOffset>("CreateDate")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTimeOffset?>("LastModified")
                                .ValueGeneratedOnAddOrUpdate()
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("AgentProfileEntityAgentProfileId");

                            b1.ToTable("AgentProfiles");

                            b1.WithOwner()
                                .HasForeignKey("AgentProfileEntityAgentProfileId");
                        });
                });

            modelBuilder.Entity("Doctrina.Domain.Entities.ResultEntity", b =>
                {
                    b.OwnsOne("Doctrina.Domain.Entities.ScoreEntity", "Score", b1 =>
                        {
                            b1.Property<Guid>("ResultEntityResultId")
                                .HasColumnType("uuid");

                            b1.Property<double?>("Max")
                                .HasColumnType("double precision");

                            b1.Property<double?>("Min")
                                .HasColumnType("double precision");

                            b1.Property<double?>("Raw")
                                .HasColumnType("double precision");

                            b1.Property<double?>("Scaled")
                                .HasColumnType("double precision");

                            b1.HasKey("ResultEntityResultId");

                            b1.ToTable("Results");

                            b1.WithOwner()
                                .HasForeignKey("ResultEntityResultId");
                        });
                });

            modelBuilder.Entity("Doctrina.Domain.Entities.StatementEntity", b =>
                {
                    b.HasOne("Doctrina.Domain.Entities.AgentEntity", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorAgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Doctrina.Domain.Entities.AgentEntity", "Authority")
                        .WithMany()
                        .HasForeignKey("AuthorityId");

                    b.HasOne("Doctrina.Domain.Entities.ContextEntity", "Context")
                        .WithMany()
                        .HasForeignKey("ContextId");

                    b.HasOne("Doctrina.Domain.Entities.ResultEntity", "Result")
                        .WithMany()
                        .HasForeignKey("ResultId");

                    b.HasOne("Doctrina.Domain.Entities.VerbEntity", "Verb")
                        .WithMany()
                        .HasForeignKey("VerbId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Doctrina.Domain.Entities.StatementObjectEntity", "Object", b1 =>
                        {
                            b1.Property<Guid>("StatementEntityStatementId")
                                .HasColumnType("uuid");

                            b1.Property<Guid?>("ActivityId")
                                .HasColumnType("uuid");

                            b1.Property<Guid?>("AgentId")
                                .HasColumnType("uuid");

                            b1.Property<int>("ObjectType")
                                .HasColumnType("integer");

                            b1.Property<Guid?>("StatementRefId")
                                .HasColumnType("uuid");

                            b1.Property<Guid?>("SubStatementId")
                                .HasColumnType("uuid");

                            b1.HasKey("StatementEntityStatementId");

                            b1.HasIndex("ActivityId");

                            b1.HasIndex("AgentId");

                            b1.HasIndex("StatementRefId");

                            b1.HasIndex("SubStatementId");

                            b1.ToTable("Statements");

                            b1.HasOne("Doctrina.Domain.Entities.ActivityEntity", "Activity")
                                .WithMany()
                                .HasForeignKey("ActivityId");

                            b1.HasOne("Doctrina.Domain.Entities.AgentEntity", "Agent")
                                .WithMany()
                                .HasForeignKey("AgentId");

                            b1.WithOwner()
                                .HasForeignKey("StatementEntityStatementId");

                            b1.HasOne("Doctrina.Domain.Entities.StatementRefEntity", "StatementRef")
                                .WithMany()
                                .HasForeignKey("StatementRefId");

                            b1.HasOne("Doctrina.Domain.Entities.SubStatementEntity", "SubStatement")
                                .WithMany()
                                .HasForeignKey("SubStatementId");
                        });
                });

            modelBuilder.Entity("Doctrina.Domain.Entities.SubStatementEntity", b =>
                {
                    b.HasOne("Doctrina.Domain.Entities.AgentEntity", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorAgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Doctrina.Domain.Entities.ContextEntity", "Context")
                        .WithMany()
                        .HasForeignKey("ContextId");

                    b.HasOne("Doctrina.Domain.Entities.ResultEntity", "Result")
                        .WithMany()
                        .HasForeignKey("ResultId");

                    b.HasOne("Doctrina.Domain.Entities.VerbEntity", "Verb")
                        .WithMany()
                        .HasForeignKey("VerbId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Doctrina.Domain.Entities.StatementObjectEntity", "Object", b1 =>
                        {
                            b1.Property<Guid>("SubStatementId")
                                .HasColumnType("uuid");

                            b1.Property<Guid?>("ActivityId")
                                .HasColumnType("uuid");

                            b1.Property<Guid?>("AgentId")
                                .HasColumnType("uuid");

                            b1.Property<int>("ObjectType")
                                .HasColumnType("integer");

                            b1.Property<Guid?>("StatementRefId")
                                .HasColumnType("uuid");

                            b1.HasKey("SubStatementId");

                            b1.HasIndex("ActivityId");

                            b1.HasIndex("AgentId");

                            b1.HasIndex("StatementRefId");

                            b1.ToTable("SubStatements");

                            b1.HasOne("Doctrina.Domain.Entities.ActivityEntity", "Activity")
                                .WithMany()
                                .HasForeignKey("ActivityId");

                            b1.HasOne("Doctrina.Domain.Entities.AgentEntity", "Agent")
                                .WithMany()
                                .HasForeignKey("AgentId");

                            b1.HasOne("Doctrina.Domain.Entities.StatementRefEntity", "StatementRef")
                                .WithMany()
                                .HasForeignKey("StatementRefId");

                            b1.WithOwner("SubStatement")
                                .HasForeignKey("SubStatementId");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
