@host = localhost:5000
@version = 1.0.3
@basicAuth = Basic YWRtaW5AZXhhbXBsZS5jb206ektSNGdrWU5IUDV0dkg=

###
POST /xapi/activities/profile?activityId=http://www.example.com/activityId/hashset&profileId=f7b6cbe5-2a15-4757-b53c-69102df7ae55 HTTP/1.1
Host: {{host}}
X-Experience-API-Version: {{version}}
Authorization: {{basicAuth}}
Accept-Encoding: gzip, deflate
User-Agent: node-superagent/1.8.5
Content-Type: application/json
Content-Length: 184

{"name":"d9ff12f9-2972-4579-8d16-69fd98b9edb8","location":{"name":"1f9b3e26-301c-4bdc-96f9-604879029980"},"75b22ce6-bb31-4b0d-a916-053801141f3a":"ea1f4644-f77a-45b6-b55d-84d58b2f25f4"}

### Delete
DELETE /xapi/activities/profile?activityId=http://www.example.com/activityId/hashset&profileId=f7b6cbe5-2a15-4757-b53c-69102df7ae55 HTTP/1.1
Host: {{host}}
X-Experience-API-Version: {{version}}
Authorization: {{basicAuth}}
Accept-Encoding: gzip, deflate
User-Agent: node-superagent/1.8.5


### GET
GET /xapi/activities/profile?activityId=http://www.example.com/activityId/hashset&profileId=f7b6cbe5-2a15-4757-b53c-69102df7ae55 HTTP/1.1
Host: {{host}}
X-Experience-API-Version: {{version}}
Authorization: {{basicAuth}}
Accept-Encoding: gzip, deflate
User-Agent: node-superagent/1.8.5

### PUT - If-None-Match: * - Prevent uploading a resource that already exist
PUT /xapi/agents/profile
    ?agent=%7B%22objectType%22%3A%22Agent%22%2C%22account%22%3A%7B%22homePage%22%3A%22http%3A%2F%2Fwww.example.com%2FagentId%2F1%22%2C%22name%22%3A%22Rick%20James%22%7D%7D
    &profileId=5852c698-e569-446c-8917-e636257e2b08 HTTP/1.1
Host: {{host}}
X-Experience-API-Version: {{version}}
Authorization: {{basicAuth}}
Accept-Encoding: gzip, deflate
User-Agent: node-superagent/1.8.5
Content-Type: application/json
If-None-Match: *
Content-Length: 184

{"name":"c47acfb8-6389-4fc7-99b2-079f63f529e8","location":{"name":"261bb42e-681b-4c47-9aba-b06392b1ee69"},"9af248da-7dcc-4743-b4eb-e252508c1444":"ca4ca3a4-8a47-4d9a-afe2-f7f2c8fba701"}

###
PUT /xapi/activities/profile
    ?activityId=http://www.example.com/activityId/hashset
    &profileId=a7950d73-0524-4411-93f9-95642481d753 HTTP/1.1
Host: localhost:5000
Accept-Encoding: gzip, deflate
User-Agent: node-superagent/1.8.5
Content-Type: application/json
If-None-Match: *
X-Experience-API-Version: 1.0.3
Authorization: Basic YWRtaW5AZXhhbXBsZS5jb206ektSNGdrWU5IUDV0dkg=
Content-Length: 184

{"name":"4767146b-5b12-4f72-89d0-5e6e6ce25846","location":{"name":"689c01d5-5e58-47b6-9a3e-653fe14b438f"},"30a9af7f-41eb-4375-8acf-942b9de61f8c":"d728fac6-99e7-44cb-b66d-fb0936e1a782"}


###