version: '3.1'

services:
  postgres-db:
    image: postgres:10.12
    restart: always
    volumes:
    - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: Testing1234
    ports:
    - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080

volumes:
  db-data:
    driver: local